### PR TITLE
Make LLVM version detection logic more robust

### PR DESCRIPTION
**Pull request by minoki**
This PR should fix https://github.com/smlsharp/smlsharp/issues/68.

### CODE REVIEW

**Comment by louy2** [comment]
Tried this out in homebrew environment, build still fails with

    command failed at status 1: getVersion /usr/local/Cellar/llvm@12/12.0.1_1/bin/llc -version

**Comment by minoki** [comment]
Since `precompiled/x86_64.ll.xz` contains the old detection logic, the build should still fail.

I thought that updating the precompiled binary should be the maintainer's job, so I didn't include the binary in this PR. But in the case it is useful to someone, I just pushed a new branch that contains the updated binary here: https://github.com/minoki/smlsharp/tree/llvm-version-detection-2

**Comment by uenoB** [comment]
Thanks for PR and sorry for late reply.

To avoid similar issues in the future, I would like to have a more robust mechanism than the current one and PR.

According to [lib/Support/CommandLine.cpp](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/CommandLine.cpp#L2403) in the LLVM source code, from LLVM 3.9.0, the LLVM version output has the following four variations depending on how the LLVM build tree is configured:

1. `"LLVM (http://llvm.org/):\n  LLVM version " PACKAGE_VERSION`
2. `"LLVM (http://llvm.org/):\n  LLVM version " PACKAGE_VERSION " " LLVM_VERSION_INFO`
3. `PACKAGE_VENDOR " LLVM version " PACKAGE_VERSION`
4. `PACKAGE_VENDOR " LLVM version " PACKAGE_VERSION " " LLVM_VERSION_INFO`

The first one is the default. The second to fourth one  is used if one or both of the `LLVM_VERSION_INFO` and `PACKAGE_VENDOR` variables are defined when LLVM is built.  Current SML# only assumes the first one. Since June 23 2021, Homebrew's llvm formula sets `PACKAGE_VENDOR` to `Homebrew` (homebrew/homebrew-core@e7c972b6062af753e564104e58d1fa20c0d1ad7a), and so this issue is brought to light. The PR is still not enough: it does not support the second and fourth ones.

I would like to take this opportunity to make the SML#'s LLVM version detection code match with the LLVM's version output format. I don't know what `PACKAGE_VENDOR` and `LLVM_VERSION_INFO` are, but perhaps taking a (whitespace-separated) word after two words "LLVM version" would be enough, I guess.

Any comments or ideas?

**Comment by uenoB** [comment]
My suggestion: uenoB/smlsharp@42ed8b9b3d53bcbc4f290d2b6fa50d7765223ca4

**Comment by minoki** [comment]
> My suggestion: [uenoB/smlsharp@42ed8b9](https://github.com/uenoB/smlsharp/commit/42ed8b9b3d53bcbc4f290d2b6fa50d7765223ca4)

Looks good to me :)

**Comment by uenoB** [comment]
> Looks good to me :)

Thanks! I will merge uenoB/smlsharp@42ed8b9b3d53bcbc4f290d2b6fa50d7765223ca4 and close this PR.

Thanks again for the PR!

**Pull request closed without merging**
