### PR TITLE
Add support for LLVM 13

### PR DESCRIPTION
**Pull request by omasanori**
While it compiles with this patch, I encountered some test failures. I am not sure if LLVM 13 causes them or not, though.

<details>
<summary>Test failures:</summary>
<pre><code>tests = 1690, failures = 4, errors = 0
Failures:
//1/SMLFormat/9/SMLFormatTest0009/11/testAssoc00R3: expected:<"(L)R">, actual:<"(L)(R)">
//1/SMLFormat/9/SMLFormatTest0009/12/testAssoc00R4: expected:<"(L)R">, actual:<"(L)(R)">
//7/DocumentTests/21/LiteralLargeConstantError: must cause a compile error
//8/ExampleTests/22/Ch07_06_01_RepresentingObject: expected:<"val it = fn : ['a#{X: 'b}, 'b. 'a ref -> 'b -> unit]

val pointClass =
  {getColor = fn, getX = fn, getY = fn, setColor = fn, setX = fn, setY = fn}
  : {getColor: ['a#{Color: 'b}, 'b. 'a ref -> 'b],
     getX: ['a#{X: 'b}, 'b. 'a ref -> 'b],
     getY: ['a#{Y: 'b}, 'b. 'a ref -> 'b],
     setColor: ['a#{Color: 'b}, 'b. 'a ref -> 'b -> unit],
     setX: ['a#{X: 'b}, 'b. 'a ref -> 'b -> unit],
     setY: ['a#{Y: 'b}, 'b. 'a ref -> 'b -> unit]}

val myPoint =
  fn
  : ['a#{Color: 'b},
     'b,
     'c#{X: 'd},
     'd,
     'e#{Y: 'f},
     'f,
     'g#{Color: 'h},
     'h,
     'i#{X: 'j},
     'j,
     'k#{Y: 'l},
     'l,
     'm.
     ({getColor: 'a ref -> 'b,
       getX: 'c ref -> 'd,
       getY: 'e ref -> 'f,
       setColor: 'g ref -> 'h -> unit,
       setX: 'i ref -> 'j -> unit,
       setY: 'k ref -> 'l -> unit}
      -> {X: real, Y: real} ref -> 'm)
     -> 'm]

val myColorPoint =
  fn
  : ['a#{Color: 'b},
     'b,
     'c#{X: 'd},
     'd,
     'e#{Y: 'f},
     'f,
     'g#{Color: 'h},
     'h,
     'i#{X: 'j},
     'j,
     'k#{Y: 'l},
     'l,
     'm.
     ({getColor: 'a ref -> 'b,
       getX: 'c ref -> 'd,
       getY: 'e ref -> 'f,
       setColor: 'g ref -> 'h -> unit,
       setX: 'i ref -> 'j -> unit,
       setY: 'k ref -> 'l -> unit}
      -> {Color: string, X: real, Y: real} ref -> 'm)
     -> 'm]

val it = () : unit

val it = 1.0 : real

val it = 0.0 : real

val it = "Red" : string
">, actual:<"val it = fn : ['a#{X: 'b}, 'b. 'a ref -> 'b -> unit]

val pointClass =
  {getColor = fn, getX = fn, getY = fn, setColor = fn, setX = fn, setY = fn}
  : {getColor: ['a#{Color: 'b}, 'b. 'a ref -> 'b],
     getX: ['a#{X: 'b}, 'b. 'a ref -> 'b],
     getY: ['a#{Y: 'b}, 'b. 'a ref -> 'b],
     setColor: ['a#{Color: 'b}, 'b. 'a ref -> 'b -> unit],
     setX: ['a#{X: 'b}, 'b. 'a ref -> 'b -> unit],
     setY: ['a#{Y: 'b}, 'b. 'a ref -> 'b -> unit]}

val myPoint =
  fn
  : ['a#{Color: 'b},
     'b,
     'c#{X: 'd},
     'd,
     'e#{Y: 'f},
     'f,
     'g#{Color: 'h},
     'h,
     'i#{X: 'j},
     'j,
     'k#{Y: 'l},
     'l,
     'm.
     ({getColor: 'a ref -> 'b,
       getX: 'c ref -> 'd,
       getY: 'e ref -> 'f,
       setColor: 'g ref -> 'h -> unit,
       setX: 'i ref -> 'j -> unit,
       setY: 'k ref -> 'l -> unit}
      -> {X: real, Y: real} ref -> 'm)
     -> 'm]

val myColorPoint =
  fn
  : ['a#{Color: 'b},
     'b,
     'c#{X: 'd},
     'd,
     'e#{Y: 'f},
     'f,
     'g#{Color: 'h},
     'h,
     'i#{X: 'j},
     'j,
     'k#{Y: 'l},
     'l,
     'm.
     ({getColor: 'a ref -> 'b,
       getX: 'c ref -> 'd,
       getY: 'e ref -> 'f,
       setColor: 'g ref -> 'h -> unit,
       setX: 'i ref -> 'j -> unit,
       setY: 'k ref -> 'l -> unit}
      -> {Color: string, X: real, Y: real} ref -> 'm)
     -> 'm]

val it = () : unit

val it = 6.93884492341E~310 : real

val it = 0.0 : real

val it = "Red" : string
">
Errors:</code></pre>
</details>

### CODE REVIEW

**Comment by uenoB** [comment]
Thank you for PR and sorry for late reply.

While this LLVM 13 support is not complete as described later, but it looks good to me in the sense that it allows the users to compile SML# with LLVM 13. The test failure is not related to LLVM 13. So, I would like to accept this PR if the commit is refined with the following suggestions:

1. Can you include the generated `configure` file in the commit, similarly to smlsharp/smlsharp@a9dd74c24e2876f8e2bd10e3c582c75909ce3fc4? We maintain `configure` in the repository along with `configure.ac` in order to avoid infection of GNU GPL.
2. Can you change the commit message to something like "Add support for LLVM 13"? Supporting a new version of LLVM is not a bugfix. Since LLVM does not preserve backward compatibility,  we need some work every time we adopt a new LLVM.

When adding support for a new version of LLVM, we check at least the following:

1. the smlsharp_gc plugin can be compiled with the new LLVM,
2. `precompile.mk` works with the new LLVM and `x86_64.ll.xz` is successfully generated, and
3. generated `x86_64.ll.xz` can be compiled with older versions of LLVM.

This PR satisfies 1 and 2, but does not satisfy 3, unfortunately. The generated `x86_64.ll.xz` cannot be compiled with LLVM 9 or earlier. To develop the SML# compiler with LLVM 13, we need a workaround to obtain backward-compatible LLVM IR code with LLVM 13. If you have a good idea for the workaround, please let me know.

Thanks again!

**Comment by omasanori** [comment]
Thank you for your thoughtful response!

> Can you include the generated configure file in the commit, similarly to a9dd74c? We maintain configure in the repository along with configure.ac in order to avoid infection of GNU GPL.

I have no idea if it is related to the conformance to GPL, but sure, I can and I will do so. Does the version of Autotools not matter, or do you have any preference?

> Can you change the commit message to something like "Add support for LLVM 13"? Supporting a new version of LLVM is not a bugfix. Since LLVM does not preserve backward compatibility, we need some work every time we adopt a new LLVM.

Yes, I will.

>  The generated x86_64.ll.xz cannot be compiled with LLVM 9 or earlier. To develop the SML# compiler with LLVM 13, we need a workaround to obtain backward-compatible LLVM IR code with LLVM 13. If you have a good idea for the workaround, please let me know.

Oh, I was unaware of that. Sorry but I have no idea.

**Comment by uenoB** [comment]
> Does the version of Autotools not matter, or do you have any preference?

Autoconf 2.69 is preferable because current `configure` is generated by it. I would like to keep the diff to a minimum.

**Comment by omasanori** [comment]
Done.

**Pull request merged**
